server:
  port: 9000

spring:
  application:
    name: record-shop-auth
  config:
    import: optional:configserver:http://localhost:8888/
  datasource:
    url: ${auth.datasource.url}
    username: ${auth.datasource.username}
    password: ${auth.datasource.password}
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"